version: '2'
services:
     reverseproxy:
          image: reverseproxy
          ports:
               - "80:80"
               - "443:443"
          restart: always
          volumes:
               - "/etc/pki/tls/certs/:/etc/ssl/certs/"
               - "/etc/pki/tls/private/:/etc/ssl/private"
     nextwave:
          image: nextwave
          ports:
               - "8080:7003"
          restart: always
