version: '2'
services:
     reverseproxy:
          image: reverseproxy
          ports:
               - "80:80"
               - "443:443"
               - "1022:1022"
          restart: always
          volumes:
               - "/etc/letsencrypt/archive/www.nextwavesolutions.io:/etc/letsencrypt/archive/www.nextwavesolutions.io"
          privileged: true
     nextwave:
          image: nextwave
          restart: always
     justynbitcoin:
             image: jbitcoin
             restart: always
     gitlab:
             image: gitlab/gitlab-ce:latest
             restart: always
             volumes:
                 - "/srv/gitlab/config:/etc/gitlab"
                 - "/srv/gitlab/logs:/var/log/gitlab"
                 - "/srv/gitlab/data:/var/opt/gitlab"
