version: '2'
services:
     reverseproxy:
          image: reverseproxy
          ports:
               - "7001:7001"
          restart: always
          volumes:
               - "/etc/pki/tls/certs/:/etc/ssl/certs/"
               - "/etc/pki/tls/private/:/etc/ssl/private"
     nextwave:
          image: nextwave
          ports:
               - "8080:7003"
          restart: always
     nextcloud:
          image: nextcloud:fpm
          restart: always
          volumes:
               - "/var/lib/nextcloud/data:/var/www/html/config"
               - "/etc/nextcloud/config.php:/var/www/html/config/config.php"
